In [2]:
#===========================================================#
#                       Importing libs                      #
#===========================================================#
import requests
import pandas as pd
from typing import Literal
from pathlib import Path
from datetime import date
from urllib.parse import quote_plus
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus
from time import sleep
import logging
import os
import re

In [9]:
files_path = Path(os.getcwd()).resolve().parent / 'data' / 'raw'
print(files_path)

/mnt/c/Projetos/fish-trade-analytics/data/raw

In [31]:
df_imports = pd.read_parquet(f'{files_path}/fish_trade_import_200601_202603.parquet')
df_exports = pd.read_parquet(f'{files_path}/fish_trade_export_200601_202603.parquet')

In [22]:
display(df_imports.info())

<class 'pandas.DataFrame'>
RangeIndex: 18820 entries, 0 to 18819
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   noMunMinsgUf  18820 non-null  str
 1   year          18820 non-null  str
 2   monthNumber   18820 non-null  str
 3   country       18820 non-null  str
 4   state         18820 non-null  str
 5   headingCode   18820 non-null  str
 6   heading       18820 non-null  str
 7   metricFOB     18820 non-null  str
 8   metricKG      18820 non-null  str
 9   ingested_at   18820 non-null  datetime64[us]
dtypes: datetime64[us](1), str(9)
memory usage: 4.5 MB

None

In [24]:
df_imports = df_imports.astype({
    'metricFOB': float,
    'metricKG': float,
    'year': int,
    'monthNumber': int,
})

In [25]:
display(df_imports.info())

<class 'pandas.DataFrame'>
RangeIndex: 18820 entries, 0 to 18819
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   noMunMinsgUf  18820 non-null  str
 1   year          18820 non-null  int64
 2   monthNumber   18820 non-null  int64
 3   country       18820 non-null  str
 4   state         18820 non-null  str
 5   headingCode   18820 non-null  str
 6   heading       18820 non-null  str
 7   metricFOB     18820 non-null  float64
 8   metricKG      18820 non-null  float64
 9   ingested_at   18820 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(5)
memory usage: 4.2 MB

None

In [30]:
print('Mostrando o top 10 estados que mais importaram em relação ao valor de importação no ano de 2025')
display(
    df_imports[df_imports['year'] == 2025]
    .groupby(['state'])['metricFOB']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

Mostrando o top 10 estados que mais importaram em relação ao valor de importação no ano de 2025

               state    metricFOB
0          São Paulo  226537093.0
1     Santa Catarina  106128077.0
2     Rio de Janeiro   45934176.0
3       Minas Gerais   22435240.0
4         Pernambuco   15297025.0
5  Rio Grande do Sul    9016577.0
6            Alagoas    6841606.0
7           Rondônia    6732391.0
8              Bahia    3378728.0
9             Paraná    2830933.0

In [32]:
display(df_exports.info())

<class 'pandas.DataFrame'>
RangeIndex: 22474 entries, 0 to 22473
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   noMunMinsgUf  22474 non-null  str
 1   year          22474 non-null  str
 2   monthNumber   22474 non-null  str
 3   country       22474 non-null  str
 4   state         22474 non-null  str
 5   headingCode   22474 non-null  str
 6   heading       22474 non-null  str
 7   metricFOB     22474 non-null  str
 8   metricKG      22474 non-null  str
 9   ingested_at   22474 non-null  datetime64[us]
dtypes: datetime64[us](1), str(9)
memory usage: 5.4 MB

None

In [33]:
df_exports = df_exports.astype({
    'metricFOB': float,
    'metricKG': float,
    'year': int,
    'monthNumber': int,
})

In [34]:
display(df_exports.info())

<class 'pandas.DataFrame'>
RangeIndex: 22474 entries, 0 to 22473
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   noMunMinsgUf  22474 non-null  str
 1   year          22474 non-null  int64
 2   monthNumber   22474 non-null  int64
 3   country       22474 non-null  str
 4   state         22474 non-null  str
 5   headingCode   22474 non-null  str
 6   heading       22474 non-null  str
 7   metricFOB     22474 non-null  float64
 8   metricKG      22474 non-null  float64
 9   ingested_at   22474 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(5)
memory usage: 5.1 MB

None

In [35]:
print('Mostrando o top 10 estados que mais exportaram em relação ao valor de importação no ano de 2025')
display(
    df_exports[df_exports['year'] == 2025]
    .groupby(['state'])['metricFOB']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

Mostrando o top 10 estados que mais exportaram em relação ao valor de importação no ano de 2025

                 state   metricFOB
0                 Pará  19531343.0
1                Ceará  19421981.0
2  Rio Grande do Norte  10026200.0
3            São Paulo   8690574.0
4               Paraná   8238110.0
5       Santa Catarina   6548330.0
6    Rio Grande do Sul   3623698.0
7           Pernambuco   3087219.0
8       Espírito Santo   3029893.0
9                Bahia   2769201.0